03-lection-01-button
js-tasks-ru/htmlcss-20210812_skorikov-denis-o pull request #3
Opened 2021-08-18 20:28 UTC by skorikov-d

2021-08-18 20:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-20 07:36 UTC, GSemikozov requested changes

2021-08-20 07:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +:root {
различные глобальные вещи надо определять в main.css

2021-08-20 07:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button {
в БЭМ селекторы тегов не используем, здесь нужно прописать именно класс блока .button

2021-08-20 07:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
такой курсор должен быть у кнопки по умолчанию, и тогда не придется его задавать явно в различных состояниях

2021-08-20 07:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
обычно вместо такого курсора используют pointer-events: none - и тогда пользователь не сможет никак взаимодействовать с disabled элементом

2021-08-20 07:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
box-sizing и border-radius должны быть указаны на ровне .button

2021-08-20 07:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-radius: 8px;
и в предыдущему комменту - указывать дополнительно box-sizing + border-radius + cursor на ховер будет ошибкой

2021-08-23 14:00 UTC, skorikov-d commented on 03-lection1/01-button/button.css
> +:root {
исправлено

2021-08-23 14:00 UTC, skorikov-d commented on 03-lection1/01-button/button.css
> +button {
исправлено

2021-08-23 14:00 UTC, skorikov-d commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
исправлено

2021-08-23 14:00 UTC, skorikov-d commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
исправлено

2021-08-23 14:00 UTC, skorikov-d commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
исправлено

2021-08-23 14:00 UTC, skorikov-d commented on 03-lection1/01-button/button.css
> +    border-radius: 8px;
исправлено

2021-09-01 13:47 UTC, GSemikozov requested changes

2021-09-01 13:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "../../assets/css/main.css";
подключается глобально на уровне всей страницы, поэтому отдельно импортировать в какие-то другие css-файлы не надо

2022-09-02 10:12 UTC, closed without merging